### ISSUE TITLE
Handle localStorage if not defined (isomorphic)

### ISSUE THREAD

**Issue by ruprict** [elgerlambert/redux-localstorage#13] opened 2015-09-11 15:08 UTC
We get the following with the 1.0 breaking changes branch when firing up the server:

```
/Users/whatevs/projects/stuff/ui/node_modules/redux-localstorage/lib/persistState.js:29
var defaultStorage = (0, _adaptersLocalStorage2['default'])(localStorage);
                                                            ^
ReferenceError: localStorage is not defined
    at Object.<anonymous> (/Users/whatevs/projects/stuff/ui/node_modules/redux-localstorage/lib/persistState.js:29:61)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/whatevs/projects/stuff/ui/node_modules/redux-localstorage/lib/index.js:17:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
 +407ms
```

I presume this is b/c of the server-side rendering. So, I added this to fix it in persistState.js:

```
if (typeof window === "undefined" ) {
  require('fs');
  var LocalStorage = require('node-localstorage').LocalStorage;
  localStorage = new LocalStorage('./scratch');
} else {
  localStorage = window.localStorage;
}
// this is existing 
var defaultStorage = (0, _adaptersLocalStorage2['default'])(localStorage);
```

It adds a dependency on node-localstorage, but that doesn't seem _too_ unreasonable...does it?

Thoughts?

**Comment by barakcoh** [comment] 2015-09-13 00:02
I'm having the same issue but w/ React Native so the proposed solution doesn't really work for me.

**Comment by ruprict** [comment] 2015-09-14 13:45
@barakcoh could we create a stub that just noops get and put? Or is there an equivalent for native that you know of?

**Comment by barakcoh** [comment] 2015-09-14 13:52
@ruprict, React Native has [Async Storage](https://facebook.github.io/react-native/docs/asyncstorage.html) however, it's async so not sure if it's a good fit.

**Comment by ruprict** [comment] 2015-09-14 13:59
Well, there's an [Async adapter](https://github.com/elgerlambert/redux-localstorage/blob/1.0-breaking-changes/src/adapters/AsyncStorage/adapter.js) for this module.  The real issue is that it defaults to `LocalStorage` when bootstrapping. Maybe we should do a test for what's available or not default it at all?

**Comment by rt2zz** [comment] 2015-09-14 21:43
what is the desired behaivor here? I would imagine you would not compose persistState at all server side. I suppose on the server side it could be used as some sort of cache...

**Comment by elgerlambert** [comment] 2015-09-15 19:08
Hi guys, thanks for raising this issue!

The straightforward fix, I think, is to remove 'const defaultStorage = adapter(localStorage);' at the top of persistState.js and replace the remaining three 'defaultStorage' values with 'adapter(localStorage)'. This ensures all 'adapter(localStorage)' assignments only happen if no storage is specified. This is effectively the same as it was before (before this became an issue). Would this solve/provide a clear solution for all (edge) cases?

My concern with a noop type solution is that this will lead to silent failures, thus leading to unexpected behaviour.

**Comment by barakcoh** [comment] 2015-09-15 19:48
Sounds good to me. a footnote in the docs should help avoid the silent failures.

**Comment by ruprict** [comment] 2015-09-15 19:52
:+1:

**Comment by igl** [comment] 2015-10-12 12:07
Even with this fixed i get:

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting.

Using the local storage in a store enhancer is probably not be a good way to do this unisomorphical.

**Comment by elgerlambert** [comment] 2015-10-15 14:48
Hi @igl, are you able to provide a little more info about your setup?

Redux-localstorage shouldn't effect the initial markup since redux's init action is dispatched first. An action to rehydrate the locally persisted data is dispatched thereafter.. I wonder though whether, due to the synchronous nature of localStorage the changes might be batched together.. (You could test this by writing a storage enhancer that makes the `get` call async by adding a timeout.)

Using the callback argument of `persistState` to delay rendering of your app until it is finished rehydrating the store will also cause a difference between what was rendered server side and what is initially rendered client side. Are you utilising the callback argument?

**Comment by igl** [comment] 2015-10-16 09:39
Hey,
No i wasn't using a callback. I only defined a `.slicer` and a `.merge`.
I no longer implicitly store stuff in local storage now but instead save and load from within a action creator. Just like you would do it talking with your backend api.
I feel it's a nicer way to contain all side effects in the action creator.

**Comment by elgerlambert** [comment] 2015-10-16 12:07
Hi @igl, thanks for replying. Based on your comment it's clear you were using `0.4.0` whereas my previous comment and the fix proposed in this issue refers to `1.0.0-rc4`, which has a [significantly different API](https://github.com/elgerlambert/redux-localstorage/tree/1.0-breaking-changes).

You're right about `0.4.0`, it doesn't support "unimorphical" apps since store rehydration happens synchronously (before your app has a chance to render the initial markup), `1.0.0` will allow you to perform server-side rendering (previous rc/beta versions already did), without getting in the way.

**Comment by Kuzmin** [comment] 2015-11-08 02:47
I'm on 1.0.0-rc4 on React Native and I still get

    Can't find variable: localStorage
    persistState.js:29

Is this still expected and am I supposed to patch this myself? Just curious since I didn't feel it was clear from the above conversation if this should be fixed or not yet.

**Comment by mdziekon** [comment] 2015-11-08 03:01
@Kuzmin - I've just [made a PR](https://github.com/elgerlambert/redux-localstorage/pull/26), based on one of the comments above, which _should_ solve this issue. I've tested it on my node.js app build, but couldn't test it on React Native (as I have never used it before).

@elgerlambert - Could you please check my PR and include it in the next RC release if it's ok with you?

**Comment by Kuzmin** [comment] 2015-11-08 06:09
@mdziekon I looked at the code that Babel outputs from your source and it looks like that would solve the problem!

**Comment by hoodsy** [comment] 2016-01-09 02:16
@elgerlambert is there any solution for this? I'm getting the same issue (on rc4)

**Comment by mdziekon** [comment] 2016-01-09 02:50
@hoodsy My PR (fixing the problem) got merged already, but apparently it has not been deployed to npm yet.

**Comment by hoodsy** [comment] 2016-01-09 02:57
@mdziekon ah ok. thanks, was hard to tell from the compiled code.

**Comment by hoodsy** [comment] 2016-01-09 14:30
@mdziekon would u mind sharing ur store config? With the changed of your PR, I'm using a workaround:
```
const isBrowser = typeof window !== 'undefined'
const target = isBrowser ? window.localStorage : ''
```
Maybe you have a better way though?

**Comment by hoodsy** [comment] 2016-01-12 22:52
@elgerlambert any plans to push the update to npm? I still get the error:
```
node_modules/redux-localstorage/lib/persistState.js:29
var defaultStorage = (0, _adaptersLocalStorage2['default'])(localStorage);
                                                            ^

ReferenceError: localStorage is not defined
```

**Comment by elgerlambert** [comment] 2016-06-14 15:52
1.0.0-rc5 is out and includes this fix! My apologies that it took so long.

**Closed by elgerlambert** 2016-06-14 15:52 UTC

**Comment by azz0r** [comment] 2016-10-17 15:05
FYI using that RC I get

``` js
/Users/azz0r/Sites/Personal/react-base-kit/node_modules/redux-localstorage/lib/persistState.js:73
      finalStorage.get(finalKey, function (err, persistedState) {
                  ^

TypeError: Cannot read property 'get' of undefined
    at /Users/azz0r/Sites/Personal/react-base-kit/node_modules/redux-localstorage/lib/persistState.js:73:19
```

**Comment by Kuzmin** [comment] 2016-10-18 09:39
@azz0r When using that RC in an environment where you don't have access to localStorage, you will need to explicitly pass in an adapter for the storage module that you want to use. Does this seem like it could be the issue?

**Comment by Rajat421** [comment] 2017-01-31 11:59
hi i want to make request to get data in getintialprops() method of next.js which execute at server side but to fetch data i have to send auth token in headers which was stored in local storage ....,so how can i get auth token at server side ..

**Comment by natkaratkova** [comment] 2018-09-13 09:58
it doesn't work for me
"redux-localstorage": "^1.0.0-rc5", 

```
ReferenceError: window is not defined
    at getDefaultStorage(..../persistState.js:30:42)
```
